# How to Deal with Missing Data in Python

## Learning Objectives
During the process of data exploration, it is not uncommon to realize that the data we have is incomplete. Missing data could arise as a result of changes in data collection methods, human error, bias, or simply the lack of reliable input. There are several ways to deal with missing data. By the end of the tutorial, you will have learned:

+ how to detect missing data
+ how to remove missing data
+ how to resolve missing data

## How to Detect Missing Values

In [1]:
import pandas as pd
students = pd.read_excel("students.xlsx")
students

,ID,FirstName,LastName,Major,Minor,Age,Gender,City,State,Zip
0,1869,Hana,Barton,Finance,NaN,22.0,Female,NaN,NaN,NaN
1,2010,Alicia,Kanuri,Management,NaN,21.0,Female,Berrien Springs,NaN,NaN
2,2075,Becca,Swanson,Marketing,NaN,22.0,Female,Chicago,IL,60608.0
3,2228,Halima,Aminu,Business Analytics,NaN,20.0,Female,Atlanta,GA,30303.0
4,2442,Holly,Robinson,Finance,NaN,20.0,Female,Charlotte,NC,28202.0
5,2858,Carla,Harding,Accountancy,NaN,NaN,Female,Youngstown,OH,44502.0
6,3459,Alex,Swanson,Accountancy,NaN,NaN,NaN,Granger,IN,NaN
7,3585,Aminah,Zalim,Marketing,NaN,20.0,Female,Ashburn,VA,20147.0
8,5170,Gus,Cunningham,Finance,Innovation,21.0,Male,Massillon,OH,44646.0
9,5317,Rafael,Solis,Business Analytics,ACMS,NaN,NaN,South Bend,IN,46601.0
10,5336,Homer,White,Finance,NaN,NaN,Male,St. Paul,MN,55101.0
11,5495,Lara,Woods,Accountancy,NaN,NaN,NaN,Dallas,TX,75201.0
12,6453,Otis,Johnson,Management,Political Science,19.0,Male,Anchorage,AK,99501.0
13,6504,Chantelle,Woods,Business Technology,NaN,18.0,Female,Chicago,NaN,60608.0
14,6768,Caroline,Marsh,Business Analytics,ACMS,22.0,Female,Niles,MI,NaN
15,7511,Laila,Carroll,Marketing,Innovation,20.0,Female,New York,NY,10001.0
16,7965,Rocco,Decola,Finance,Innovation,21.0,Male,Oakland,CA,94603.0
17,9232,Julie,Holmes,Business Technology,Innovation,18.0,Female,Webster,NY,14580.0
18,9268,Albert,Palmer,Management,Real Estate,21.0,Male,Detroit,MI,48201.0
19,9941,Zoya,Doyle,Business Analytics,NaN,NaN,Female,Chicago,IL,60608.0

In [8]:
mask = students['State'].isnull()
mask

0      True
1      True
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13     True
14    False
15    False
16    False
17    False
18    False
19    False
Name: State, dtype: bool

In [6]:
students[mask]

,ID,FirstName,LastName,Major,Minor,Age,Gender,City,State,Zip
0,1869,Hana,Barton,Finance,NaN,22.0,Female,NaN,NaN,NaN
1,2010,Alicia,Kanuri,Management,NaN,21.0,Female,Berrien Springs,NaN,NaN
13,6504,Chantelle,Woods,Business Technology,NaN,18.0,Female,Chicago,NaN,60608.0

## How to Remove Missing Values

In [16]:
students.dropna()

,ID,FirstName,LastName,Major,Minor,Age,Gender,City,State,Zip
8,5170,Gus,Cunningham,Finance,Innovation,21.0,Male,Massillon,OH,44646.0
12,6453,Otis,Johnson,Management,Political Science,19.0,Male,Anchorage,AK,99501.0
15,7511,Laila,Carroll,Marketing,Innovation,20.0,Female,New York,NY,10001.0
16,7965,Rocco,Decola,Finance,Innovation,21.0,Male,Oakland,CA,94603.0
17,9232,Julie,Holmes,Business Technology,Innovation,18.0,Female,Webster,NY,14580.0
18,9268,Albert,Palmer,Management,Real Estate,21.0,Male,Detroit,MI,48201.0

In [21]:
students2 = pd.read_excel("students.xlsx")
students2 = students2.dropna(subset = ['State', 'Zip'], how = 'all')
students2

,ID,FirstName,LastName,Major,Minor,Age,Gender,City,State,Zip
2,2075,Becca,Swanson,Marketing,NaN,22.0,Female,Chicago,IL,60608.0
3,2228,Halima,Aminu,Business Analytics,NaN,20.0,Female,Atlanta,GA,30303.0
4,2442,Holly,Robinson,Finance,NaN,20.0,Female,Charlotte,NC,28202.0
5,2858,Carla,Harding,Accountancy,NaN,NaN,Female,Youngstown,OH,44502.0
6,3459,Alex,Swanson,Accountancy,NaN,NaN,NaN,Granger,IN,NaN
7,3585,Aminah,Zalim,Marketing,NaN,20.0,Female,Ashburn,VA,20147.0
8,5170,Gus,Cunningham,Finance,Innovation,21.0,Male,Massillon,OH,44646.0
9,5317,Rafael,Solis,Business Analytics,ACMS,NaN,NaN,South Bend,IN,46601.0
10,5336,Homer,White,Finance,NaN,NaN,Male,St. Paul,MN,55101.0
11,5495,Lara,Woods,Accountancy,NaN,NaN,NaN,Dallas,TX,75201.0
12,6453,Otis,Johnson,Management,Political Science,19.0,Male,Anchorage,AK,99501.0
13,6504,Chantelle,Woods,Business Technology,NaN,18.0,Female,Chicago,NaN,60608.0
14,6768,Caroline,Marsh,Business Analytics,ACMS,22.0,Female,Niles,MI,NaN
15,7511,Laila,Carroll,Marketing,Innovation,20.0,Female,New York,NY,10001.0
16,7965,Rocco,Decola,Finance,Innovation,21.0,Male,Oakland,CA,94603.0
17,9232,Julie,Holmes,Business Technology,Innovation,18.0,Female,Webster,NY,14580.0
18,9268,Albert,Palmer,Management,Real Estate,21.0,Male,Detroit,MI,48201.0
19,9941,Zoya,Doyle,Business Analytics,NaN,NaN,Female,Chicago,IL,60608.0

In [26]:
students3 = pd.read_excel("students.xlsx")
students3 = students3.dropna(axis = 1)
students3

      ID  FirstName    LastName                Major
0   1869       Hana      Barton              Finance
1   2010     Alicia      Kanuri           Management
2   2075      Becca     Swanson            Marketing
3   2228     Halima       Aminu   Business Analytics
4   2442      Holly    Robinson              Finance
5   2858      Carla     Harding          Accountancy
6   3459       Alex     Swanson          Accountancy
7   3585     Aminah       Zalim            Marketing
8   5170        Gus  Cunningham              Finance
9   5317     Rafael       Solis   Business Analytics
10  5336      Homer       White              Finance
11  5495       Lara       Woods          Accountancy
12  6453       Otis     Johnson           Management
13  6504  Chantelle       Woods  Business Technology
14  6768   Caroline       Marsh   Business Analytics
15  7511      Laila     Carroll            Marketing
16  7965      Rocco      Decola              Finance
17  9232      Julie      Holmes  Business Technology
18  9268     Albert      Palmer           Management
19  9941       Zoya       Doyle   Business Analytics

In [28]:
students4 = pd.read_excel("students.xlsx")
students4 = students.dropna(axis = 1, thresh = 10)
students4

      ID  FirstName    LastName                Major
0   1869       Hana      Barton              Finance
1   2010     Alicia      Kanuri           Management
2   2075      Becca     Swanson            Marketing
3   2228     Halima       Aminu   Business Analytics
4   2442      Holly    Robinson              Finance
5   2858      Carla     Harding          Accountancy
6   3459       Alex     Swanson          Accountancy
7   3585     Aminah       Zalim            Marketing
8   5170        Gus  Cunningham              Finance
9   5317     Rafael       Solis   Business Analytics
10  5336      Homer       White              Finance
11  5495       Lara       Woods          Accountancy
12  6453       Otis     Johnson           Management
13  6504  Chantelle       Woods  Business Technology
14  6768   Caroline       Marsh   Business Analytics
15  7511      Laila     Carroll            Marketing
16  7965      Rocco      Decola              Finance
17  9232      Julie      Holmes  Business Technology
18  9268     Albert      Palmer           Management
19  9941       Zoya       Doyle   Business Analytics

## How to Resolve Missing Values

In [33]:
students = pd.read_excel("students.xlsx")
students = students.fillna({'Gender' : 'Female'})
students

,ID,FirstName,LastName,Major,Minor,Age,Gender,City,State,Zip
0,1869,Hana,Barton,Finance,NaN,22.0,Female,NaN,NaN,NaN
1,2010,Alicia,Kanuri,Management,NaN,21.0,Female,Berrien Springs,NaN,NaN
2,2075,Becca,Swanson,Marketing,NaN,22.0,Female,Chicago,IL,60608.0
3,2228,Halima,Aminu,Business Analytics,NaN,20.0,Female,Atlanta,GA,30303.0
4,2442,Holly,Robinson,Finance,NaN,20.0,Female,Charlotte,NC,28202.0
5,2858,Carla,Harding,Accountancy,NaN,NaN,Female,Youngstown,OH,44502.0
6,3459,Alex,Swanson,Accountancy,NaN,NaN,Female,Granger,IN,NaN
7,3585,Aminah,Zalim,Marketing,NaN,20.0,Female,Ashburn,VA,20147.0
8,5170,Gus,Cunningham,Finance,Innovation,21.0,Male,Massillon,OH,44646.0
9,5317,Rafael,Solis,Business Analytics,ACMS,NaN,Female,South Bend,IN,46601.0
10,5336,Homer,White,Finance,NaN,NaN,Male,St. Paul,MN,55101.0
11,5495,Lara,Woods,Accountancy,NaN,NaN,Female,Dallas,TX,75201.0
12,6453,Otis,Johnson,Management,Political Science,19.0,Male,Anchorage,AK,99501.0
13,6504,Chantelle,Woods,Business Technology,NaN,18.0,Female,Chicago,NaN,60608.0
14,6768,Caroline,Marsh,Business Analytics,ACMS,22.0,Female,Niles,MI,NaN
15,7511,Laila,Carroll,Marketing,Innovation,20.0,Female,New York,NY,10001.0
16,7965,Rocco,Decola,Finance,Innovation,21.0,Male,Oakland,CA,94603.0
17,9232,Julie,Holmes,Business Technology,Innovation,18.0,Female,Webster,NY,14580.0
18,9268,Albert,Palmer,Management,Real Estate,21.0,Male,Detroit,MI,48201.0
19,9941,Zoya,Doyle,Business Analytics,NaN,NaN,Female,Chicago,IL,60608.0

In [35]:
students = pd.read_excel("students.xlsx")
students = students.fillna({'Age' : students['Age'].median()})
students

,ID,FirstName,LastName,Major,Minor,Age,Gender,City,State,Zip
0,1869,Hana,Barton,Finance,NaN,22.0,Female,NaN,NaN,NaN
1,2010,Alicia,Kanuri,Management,NaN,21.0,Female,Berrien Springs,NaN,NaN
2,2075,Becca,Swanson,Marketing,NaN,22.0,Female,Chicago,IL,60608.0
3,2228,Halima,Aminu,Business Analytics,NaN,20.0,Female,Atlanta,GA,30303.0
4,2442,Holly,Robinson,Finance,NaN,20.0,Female,Charlotte,NC,28202.0
5,2858,Carla,Harding,Accountancy,NaN,20.5,Female,Youngstown,OH,44502.0
6,3459,Alex,Swanson,Accountancy,NaN,20.5,NaN,Granger,IN,NaN
7,3585,Aminah,Zalim,Marketing,NaN,20.0,Female,Ashburn,VA,20147.0
8,5170,Gus,Cunningham,Finance,Innovation,21.0,Male,Massillon,OH,44646.0
9,5317,Rafael,Solis,Business Analytics,ACMS,20.5,NaN,South Bend,IN,46601.0
10,5336,Homer,White,Finance,NaN,20.5,Male,St. Paul,MN,55101.0
11,5495,Lara,Woods,Accountancy,NaN,20.5,NaN,Dallas,TX,75201.0
12,6453,Otis,Johnson,Management,Political Science,19.0,Male,Anchorage,AK,99501.0
13,6504,Chantelle,Woods,Business Technology,NaN,18.0,Female,Chicago,NaN,60608.0
14,6768,Caroline,Marsh,Business Analytics,ACMS,22.0,Female,Niles,MI,NaN
15,7511,Laila,Carroll,Marketing,Innovation,20.0,Female,New York,NY,10001.0
16,7965,Rocco,Decola,Finance,Innovation,21.0,Male,Oakland,CA,94603.0
17,9232,Julie,Holmes,Business Technology,Innovation,18.0,Female,Webster,NY,14580.0
18,9268,Albert,Palmer,Management,Real Estate,21.0,Male,Detroit,MI,48201.0
19,9941,Zoya,Doyle,Business Analytics,NaN,20.5,Female,Chicago,IL,60608.0

In [38]:
mask = (students['City'] == 'Granger') & (students['State'] == 'IN')

In [39]:
students.loc[mask, :]

     ID FirstName LastName        Major Minor  Age Gender     City State  Zip
6  3459      Alex  Swanson  Accountancy   NaN  NaN    NaN  Granger    IN  NaN

In [42]:
students.loc[mask, 'Zip'] = 46530
students

,ID,FirstName,LastName,Major,Minor,Age,Gender,City,State,Zip
0,1869,Hana,Barton,Finance,NaN,22.0,Female,NaN,NaN,NaN
1,2010,Alicia,Kanuri,Management,NaN,21.0,Female,Berrien Springs,NaN,NaN
2,2075,Becca,Swanson,Marketing,NaN,22.0,Female,Chicago,IL,60608.0
3,2228,Halima,Aminu,Business Analytics,NaN,20.0,Female,Atlanta,GA,30303.0
4,2442,Holly,Robinson,Finance,NaN,20.0,Female,Charlotte,NC,28202.0
5,2858,Carla,Harding,Accountancy,NaN,NaN,Female,Youngstown,OH,44502.0
6,3459,Alex,Swanson,Accountancy,NaN,NaN,NaN,Granger,IN,46530.0
7,3585,Aminah,Zalim,Marketing,NaN,20.0,Female,Ashburn,VA,20147.0
8,5170,Gus,Cunningham,Finance,Innovation,21.0,Male,Massillon,OH,44646.0
9,5317,Rafael,Solis,Business Analytics,ACMS,NaN,NaN,South Bend,IN,46601.0
10,5336,Homer,White,Finance,NaN,NaN,Male,St. Paul,MN,55101.0
11,5495,Lara,Woods,Accountancy,NaN,NaN,NaN,Dallas,TX,75201.0
12,6453,Otis,Johnson,Management,Political Science,19.0,Male,Anchorage,AK,99501.0
13,6504,Chantelle,Woods,Business Technology,NaN,18.0,Female,Chicago,NaN,60608.0
14,6768,Caroline,Marsh,Business Analytics,ACMS,22.0,Female,Niles,MI,NaN
15,7511,Laila,Carroll,Marketing,Innovation,20.0,Female,New York,NY,10001.0
16,7965,Rocco,Decola,Finance,Innovation,21.0,Male,Oakland,CA,94603.0
17,9232,Julie,Holmes,Business Technology,Innovation,18.0,Female,Webster,NY,14580.0
18,9268,Albert,Palmer,Management,Real Estate,21.0,Male,Detroit,MI,48201.0
19,9941,Zoya,Doyle,Business Analytics,NaN,NaN,Female,Chicago,IL,60608.0

In [43]:
mask = (students['City'] == 'Niles') & (students['State'] == 'MI')
students.loc[mask, 'Zip'] = 49120
students

,ID,FirstName,LastName,Major,Minor,Age,Gender,City,State,Zip
0,1869,Hana,Barton,Finance,NaN,22.0,Female,NaN,NaN,NaN
1,2010,Alicia,Kanuri,Management,NaN,21.0,Female,Berrien Springs,NaN,NaN
2,2075,Becca,Swanson,Marketing,NaN,22.0,Female,Chicago,IL,60608.0
3,2228,Halima,Aminu,Business Analytics,NaN,20.0,Female,Atlanta,GA,30303.0
4,2442,Holly,Robinson,Finance,NaN,20.0,Female,Charlotte,NC,28202.0
5,2858,Carla,Harding,Accountancy,NaN,NaN,Female,Youngstown,OH,44502.0
6,3459,Alex,Swanson,Accountancy,NaN,NaN,NaN,Granger,IN,46530.0
7,3585,Aminah,Zalim,Marketing,NaN,20.0,Female,Ashburn,VA,20147.0
8,5170,Gus,Cunningham,Finance,Innovation,21.0,Male,Massillon,OH,44646.0
9,5317,Rafael,Solis,Business Analytics,ACMS,NaN,NaN,South Bend,IN,46601.0
10,5336,Homer,White,Finance,NaN,NaN,Male,St. Paul,MN,55101.0
11,5495,Lara,Woods,Accountancy,NaN,NaN,NaN,Dallas,TX,75201.0
12,6453,Otis,Johnson,Management,Political Science,19.0,Male,Anchorage,AK,99501.0
13,6504,Chantelle,Woods,Business Technology,NaN,18.0,Female,Chicago,NaN,60608.0
14,6768,Caroline,Marsh,Business Analytics,ACMS,22.0,Female,Niles,MI,49120.0
15,7511,Laila,Carroll,Marketing,Innovation,20.0,Female,New York,NY,10001.0
16,7965,Rocco,Decola,Finance,Innovation,21.0,Male,Oakland,CA,94603.0
17,9232,Julie,Holmes,Business Technology,Innovation,18.0,Female,Webster,NY,14580.0
18,9268,Albert,Palmer,Management,Real Estate,21.0,Male,Detroit,MI,48201.0
19,9941,Zoya,Doyle,Business Analytics,NaN,NaN,Female,Chicago,IL,60608.0